apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-sudo-alerts
    receivers:
      - uid: discord-sudo-webhook
        type: discord
        settings:
          url: ${DISCORD_SUDO_ALERTS_WEBHOOK_URL}
          use_discord_username: true
