global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers: []

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sentinel-business-metrics'
    metrics_path: /business-metrics
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 60s

  - job_name: 'sentinel-django-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 60s

  - job_name: 'celery-flower'
    metrics_path: /metrics
    static_configs:
      - targets: ['celery-flower:5555']
    scrape_interval: 60s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
